name: Build and Deploy Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for Nginx
        run: |
          docker build -t apps-server:latest -f Dockerfile .
          docker tag apps-server:latest ${{ secrets.DOCKER_USERNAME }}/nginx_image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx_image:latest
